// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI8_7SQ7MPRk_BTYnfcY1HtMOJTTE6f9A',
    appId: '1:306407851745:web:123b327a6d622d902d19a0',
    messagingSenderId: '306407851745',
    projectId: 'farmone-2026-0910',
    authDomain: 'farmone-2026-0910.firebaseapp.com',
    storageBucket: 'farmone-2026-0910.firebasestorage.app',
    measurementId: 'G-80W2NRWJ7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUQPkWp1etxyXJErFwunR3lcAp8NED4u0',
    appId: '1:306407851745:android:017c720817910ac92d19a0',
    messagingSenderId: '306407851745',
    projectId: 'farmone-2026-0910',
    storageBucket: 'farmone-2026-0910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdygDk-02ato5s3xN9Sa9rwhCbSSZdS68',
    appId: '1:306407851745:ios:08511a2a7e0a17102d19a0',
    messagingSenderId: '306407851745',
    projectId: 'farmone-2026-0910',
    storageBucket: 'farmone-2026-0910.firebasestorage.app',
    iosBundleId: 'com.farmconnect.farmconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdygDk-02ato5s3xN9Sa9rwhCbSSZdS68',
    appId: '1:306407851745:ios:08511a2a7e0a17102d19a0',
    messagingSenderId: '306407851745',
    projectId: 'farmone-2026-0910',
    storageBucket: 'farmone-2026-0910.firebasestorage.app',
    iosBundleId: 'com.farmconnect.farmconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI8_7SQ7MPRk_BTYnfcY1HtMOJTTE6f9A',
    appId: '1:306407851745:web:d4a868fd3c64cf832d19a0',
    messagingSenderId: '306407851745',
    projectId: 'farmone-2026-0910',
    authDomain: 'farmone-2026-0910.firebaseapp.com',
    storageBucket: 'farmone-2026-0910.firebasestorage.app',
    measurementId: 'G-96KSWB67J8',
  );
}
